name: Auto Rerun Failed Workflow

# This workflow is triggered manually and by repository_dispatch. It checks
# the latest run of the specified workflow and if it failed it requests a rerun.

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        description: 'Workflow file name (e.g. Publish Worker Image)'
        required: true

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Rerun last failed
        uses: devops-infra/action-rerun-workflow@v2
        with:
          workflow: ${{ github.event.inputs.workflow_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
