const fs = require('fs');
const path = require('path');

// Lightweight prepare script to create a simple pre-commit hook calling lint-staged.
// This is idempotent and safe to run in CI or locally.
(function main(){
  const repoRoot = path.join(__dirname, '..');
  const huskyDir = path.join(repoRoot, '.husky');
  try {
    if (!fs.existsSync(huskyDir)) fs.mkdirSync(huskyDir, { recursive: true });
    const hookPath = path.join(huskyDir, 'pre-commit');
    const hookContent = `#!/bin/sh\n# Generated by scripts/prepare-husky.js\n# Run lint-staged as pre-commit check\nnpx --no-install lint-staged || exit 1\n`;
    fs.writeFileSync(hookPath, hookContent, { encoding: 'utf8', mode: 0o755 });
    console.log('Prepared husky pre-commit hook at', hookPath);
  } catch (e) {
    console.error('Failed to prepare husky hooks:', e && e.message ? e.message : e);
    process.exitCode = 1;
  }
})();
