name: Debug CI
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Echo
        run: |
          echo "Debug run"
          uname -a
          env | sort
