name: Monitor JasnePismo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Run monitoring script
        run: node ./scripts/check-monitor.js
        env:
          TARGET_URL: https://www.jasnepismo.pl
